### ISSUE TITLE
/restapi/v1.0 is prepended to SCIM urls

### ISSUE THREAD

**Issue by erfaan** [ringcentral/ringcentral-python#13] opened 2018-02-02 15:05 UTC
When I try to fetch Users list via SCIM URI using:

`platform.get("/scim/v2/Users")`

It is automatically converted to `https://platform.devtest.ringcentral.com/restapi/v1.0/scim/v2/Users`

i.e. `/restapi/v1.0` prepended to the URL.

and results in "Invalid URI" exception.

**Comment by kirill-konshin** [comment] 2018-02-02 18:33
This SDK is intended to be used with RingCentral, that's why all URLs are prefixed. Are you using it with a different backend?

**Comment by kirill-konshin** [comment] 2018-02-02 21:01
I don't think that it's a good idea to change logic of slash handling. Instead, I can add a `/scim/` prefix handler.

**Comment by grokify** [comment] 2018-02-02 23:35
I like the idea of changing the slash handling logic because it's a more generic and easily understandable approach where a leading slash means a base path. This is how the `ringcentral_sdk` Ruby gem is designed. That being said, it is a breaking change here so special `/scim/` handling may be the way to go for this library.

**Comment by kirill-konshin** [comment] 2018-02-03 00:00
It's a breaking change, so it's a no go. Unless we want to release a new major version. But for such change major version is a bit too much.

**Comment by tylerlong** [comment] 2018-02-08 01:39
Hi, for those who are stuck on this. Please try https://github.com/tylerlong/ringcentral-python. It doesn't prepend anything to the url you specified.  It is unofficial. And I only recommend it as a temporary workaround before the official SDK fix this issue.

**Comment by grokify** [comment] 2018-03-03 16:46
There was a good proposal presented for this:

* Allow leading slashes to mean root, except when known `/restapi/v1.0` endpoints are used, then prepend `/restapi/v1.0`.

This approach accomplishes two goals:

* Supports expected behavior
* Does not break backward compatibility

Support expected behavior allows us to use the following principles:

POLA - Priciple of Least Astonishment: https://en.wikipedia.org/wiki/Principle_of_least_astonishment
DWIM - Do What I Mean: https://en.wikipedia.org/wiki/DWIM

**Comment by kirill-konshin** [comment] 2018-03-03 21:26
Nice proposal, but it's not safe. If a new endpoint will be introduced and used under `/restapi/v1.0` then behavior will be inconsistent. Imagine the astonishment in this case.

**Comment by grokify** [comment] 2018-03-04 08:24
The URL building magic seems to be more trouble than it's worth given the unpredictable nature of new APIs. If we provide a deprecation notice saying this should no longer be used, then there should be no astonishment for new APIs in the future.

I think we should consider moving the URL building magic into a stand-alone function. People can call it and build the URL separately if they wish. I'm not sure it should be a built-in feature of the SDK.

**Comment by grokify** [comment] 2018-03-04 18:01
Regarding breaking changes, the original goal of keeping this a sub-1.0 release is that we wanted to make breaking changes. If this is no longer the case and we are treating this as a production 1.0 release, we should consider bumping the version to 1.0, at which time we can also introduce the leading slash at root breaking change behavior.

**Comment by kirill-konshin** [comment] 2018-03-05 19:15
Released 0.7.8 with the quick fix. Now since the issue is fixed we can discuss what else we want in 1.0.0 or any other update.

**Closed by kirill-konshin** 2018-03-05 19:15 UTC
